version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      # 永続化するときにマウントするdir
      - ./data/mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      # 永続化するときにマウントするdir
      - ./data/redis:/data

  sidecar_redis:
    image: redis:latest
    container_name: sidecar_redis_local
    ports:
      - ${SIDECAR_REDIS_PORT}:6379
    volumes:
      # 永続化するときにマウントするdir
      - ./data/sidecar_redis:/data
